"""create user bio and user profile pic  column

Revision ID: 295855bf139a
Revises: 9b8ee56ca2c4
Create Date: 2019-11-30 11:05:41.636369

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '295855bf139a'
down_revision = '9b8ee56ca2c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('blog_id', sa.String(), nullable=True),
    sa.Column('user', sa.String(), nullable=True),
    sa.Column('blog_comment', sa.String(), nullable=True),
    sa.Column('posted', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('users', sa.Column('bio', sa.String(), nullable=True))
    op.add_column('users', sa.Column('profile_path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'profile_path')
    op.drop_column('users', 'bio')
    op.drop_table('comment')
    # ### end Alembic commands ###
