"""create user pass_code column

Revision ID: caf240851564
Revises: 4369a7d925fa
Create Date: 2019-11-28 12:11:24.880449

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'caf240851564'
down_revision = '4369a7d925fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('pass_code', sa.String(length=16), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'pass_code')
    # ### end Alembic commands ###
